# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Spotify
version: "1.1.0"
slug: spotify
description: Example add-on
url: "https://github.com/limacher58/Spotify_homeassistant/spotify"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
